### ISSUE TITLE
Entire prefix in properties

### ISSUE THREAD

**Issue by pschichtel** [adapta-project/adapta-backgrounds#1]
When packaging the project, I'll set the prefix for autogen to $pkgdir/usr which correctly builds to files into the packaging direcktory during make install. The problem is, that the entire prefix is used in the image path in the properties file, instead of just `/usr/...`.

I currently work around it by removing the packaging dir from the final XML.

**Comment by tista500** [comment]
Please send us PR...

Regards.

**Comment by tista500** [comment]
This could work? https://github.com/adapta-project/adapta-backgrounds/commit/94b040776eb3ec1c6086971b08fe0b7c5c4c3828

**EDIT**
None, bad commit... :(

**Comment by tista500** [comment]
Please check out https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gnome-backgrounds

**Comment by pschichtel** [comment]
the DESTDIR parameter does the trick. Interesting, that this was not necessary for the theme package...
Thanks for the hint :)
