### ISSUE TITLE
PNG versions

### ISSUE THREAD

**Issue by txtsd** [adapta-project/adapta-backgrounds#2]
Could you include PNG versions of the wallpapers too, please?

**Comment by tista500** [comment]
What is the purpose to dup those images? I don't have any ideas why we have to do so...

Regards.

**Comment by txtsd** [comment]
Then include only PNGs. Why choose a lossy format to provide UHD wallpapers?

**Comment by tista500** [comment]
It's enough with jpeg formatting. See https://git.gnome.org/browse/gnome-backgrounds/tree/backgrounds

Closed.

**Comment by txtsd** [comment]
Could you, at least, provide a way to re-create these wallpapers (source, xcf, psd)?
